### ISSUE TITLE
access to path denied

### ISSUE THREAD

**Issue by jeffythedragonslayer** [Dom-aka-Doke/Advanced-SNES-ROM-Utility#10] opened 2022-07-03 20:50 UTC
I am getting this error even when I run the exe as administrator.  There isn't too much information on why access is denied...

![image](https://user-images.githubusercontent.com/13253146/177056841-4da71aa5-a9c7-40d4-9a5b-72f55dd683cb.png)

**Comment by Dom-aka-Doke** [comment] 2022-07-04 06:56
Can you try it with another folder? Have you checked your event log? Maybe there's something wrong with your local folder permissions or the file/folder is used by another process? I never run into this kind of issues.

**Comment by Dom-aka-Doke** [comment] 2022-07-05 09:37
I think I'm gonna close this issue for now, until proof is provided that this is an error caused by this application.
Local permission or access problems can't be solved by code.
Only thing I can do is handling exceptions on opening files in a more user friendly way and prevent application from crashing.
If you have further questions, please don't hesitate.

**Closed as completed by Dom-aka-Doke** 2022-07-05 09:37 UTC
